# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci():
    numbers = []
    number_one = 1
    number_two = 2
    while True:
        numbers.append(number_one)
        number = number_one
        number_one = number_two
        number_two = number + number_two
        if number_one > 4000000:
            return numbers

def sum_of_even(numbers):
    sum = 0
    for i in numbers:
        if i % 2 == 0:
            sum = sum + i
    return sum

numbers = fibonacci()

answer = sum_of_even(numbers)

print(answer)
